default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["DESAFIO_DEV_BACKEND_JR_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: desafio_dev_backend_jr_development

test:
  <<: *default
  database: desafio_dev_backend_jr_test

production:
  <<: *default
  database: desafio_dev_backend_jr_production
